---
- name: Deploy
  hosts: web
  become: yes
  
  tasks:
    - name: copy
      copy:
       src: target/web.war
       dest: /opt/tomcat/webapps/web.war
       
    - name: stop
      shell: /opt/tomcat/bin/shutdown.sh
      
    - name: start
      shell: /opt/tomcat/bin/startup.sh
      

